import type { Metadata } from "next"
import AppProvider from "./_src/providers/AppProviders"
import "./globals.css"

export const metadata: Metadata = {
  title: "Trauma Clown",
  description: "Generated by create next app",
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <AppProvider>
        <body>{children}</body>
      </AppProvider>
    </html>
  )
}

export default RootLayout
