import type { Metadata } from "next"
import StoreProvider from "./StoreProvider"
import "./globals.css"

export const metadata: Metadata = {
  title: "Trauma Clown",
  description: "Generated by create next app",
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <StoreProvider>
        <body>{children}</body>
      </StoreProvider>
    </html>
  )
}

export default RootLayout
